### PR TITLE
Switch cdo by ECMWF GPH computation.

### PR DESCRIPTION
**Pull request by joernu76**

### CODE REVIEW

**Review by gisi90 — CHANGES_REQUESTED** [review]
Great workflow now. Only ran into one issue with $tmp2 when sfc is merged with tmp:

converting sfc
cdo    copy: Processed 77469 values from 7 variables over 7 timesteps [0.02s 14MB].
cdo    copy: Processed 11067 values from 1 variable over 7 timesteps [0.37s 52MB].

cdo    merge (Abort): Outputfile mss/.XXXXXX.036.tmp already exists!


in convert.sh:
`
#extract lnsp and remove lev dimension.
grib_copy -w shortName=lnsp grib/${BASE}.ml2.grib ${tmpfile}
cdo -f nc4c -t ecmwf copy ${tmpfile} ${tmpfile}2
ncwa -O -alev ${tmpfile}2 ${tmpfile}
ncks -7 -C -O -x -vhyai,hyam,hybi,hybm,lev ${tmpfile} ${tmpfile}2
cdo merge ${sfcfile} ${tmpfile}2 ${tmpfile}3
mv ${tmpfile}3 $sfcfile
rm ${tmpfile}2
rm ${tmpfile}3
`

**Review by gisi90 — APPROVED** [review]
Please change BASE in get_ecmwf.sh to
export BASE=${YMD}_${HH}_ecmwf_forecast.${FILENAME}.${FCSTEP}

Otherwise all is working without errors. Good job.

**Comment by joernu76** [comment]
> Please change BASE in get_ecmwf.sh to export BASE=${YMD}_${HH}_ecmwf_forecast.${FILENAME}.${FCSTEP}
> 
> Otherwise all is working without errors. Good job.

I have used DATASET instead of filename, which I deemed more fitting. As such the functionality is there.

We should discuss the definition of BASE offline. MSS actually does not care, but we might.

I'd like to merge this now as the proper naming of our files is a separate issue.

**Comment by joernu76** [comment]
Fix #25
Fix #17 
Fix #24

**Pull request merged**
